var MiamiInfo = "Team: Miami Heat Current Season: W54-L­28 Team Color Red,Black,white Best PLayer: Dwyane Wade Rings: 3 Coach: Erik Spoelstra President: Pat Riley City: MiamiConference: Southeastern Champion Seasons: 2006, 2012,2013 Owner: Micky Arison Rivalries: NY, OL, CH,BO,IN Arena: American Airlines Arena";
						
						
						
						
						

var Miami = [
						"An expansion team formed in 1988, the Miami Heat began their early years with much mediocrity, only making the playoffs two times in their first eight years and falling in the first round both times. Upon the purchasing of the franchise by Micky Arison in 1995, Pat Riley was brought in as the team president and head coach. Riley acquired center Alonzo Mourning and point guard Tim Hardaway to serve as the centerpiece for the team, transforming Miami into a championship contender throughout the late 1990s.",
						"In the 2003 NBA Draft, with the fifth overall pick, Miami selected shooting guard Dwyane Wade out of Marquette.[3] Free­agent swing­man Lamar Odom was signed from the Los Angeles Clippers. Just prior to the start of the 03–04 season, Riley stepped down as head coach to focus on rebuilding the Heat, promoting Stan Van Gundy to the position of head coach. Behind Van Gundy's leadership, Wade's stellar rookie year and Odom's break out season, the Heat made the 2004 NBA Playoffs, beating the New Orleans Hornets 4–3 in the 1st round and losing to the Indiana Pacers 4–2 in the 2nd round. In the offseason, Riley engineered a summer blockbuster trade for Shaquille O'Neal from the Los Angeles Lakers.",
						'Entering the 2010–2011 season with nearly $48 million in salary cap space, the Heat caused a major power shift during the blockbuster 2010 NBA Free Agency, adding Chris Bosh and LeBron James to local superstar Dwyane Wade, starting the "Big 3" era. However, the Heat got off to an 8–14 start. After a "players only" meeting, the team pulled together. The Heat finished with a 58–24 record and the 2nd seed. In the much anticipated 2011 NBA Playoffs, Miami defeated the Philadelphia 76ers in the first round, Boston Celtics in the Conference Semifinals, and Bulls in the Conference Finals, all in 5 games. The Heat reached the 2011 NBA Finals for the first time since 2006, in a rematch against the Dallas Mavericks.',
];

var LakersInfo = 'Team: Los Angeles Lakers Current Season: 45­-37 Team Color Purple,Gold,white Best Player: Kobe Bryant Rings: 16 Coach: Vacant President: Mitch KupchakCity: LA California Conference: Western Pacific Champion Seasons: (1949, 1950, 1952, 1953, 1954, 1972, 1980, 1982, 1985, 1987, 1988, 2000, 2001, 2002, 2009, 2010) Owner: Jerry Buss Rivalries:BO,LA Clippers, Spurs Arena: Staples Center';





var Lakers = [
						'The Lakers franchise began in 1947 when Ben Berger and Morris Chalfen of Minnesota purchased the recently disbanded Detroit Gems of the National Basketball League (NBL) for $15,000 from Gems owner Maury Winston. Minneapolis sportswriter Sid Hartman played a key behind the scenes role in helping put together the deal and later the team.[9] Inspired by Minnesotas nickname, "Land of 10,000 Lakes", the team christened themselves the Lakers.[4][10] Hartman helped them hire John Kundla from College of St. Thomas, to be their first head coach, by meeting with him and selling him on the team.',
						'On July 9, 1968, the team acquired Wilt Chamberlain from the Philadelphia 76ers for Darrell Imhoff, Archie Clark, and Jerry Chambers.[48] In his first season as a Laker, Chamberlain set a team record by averaging a league­leading 21.1 rpg.[49] West, Baylor, and Chamberlain each averaged over 20 points, and Los Angeles won their division.[50] The Lakers and Celtics again met in the finals, and Los Angeles had home court advantage against Boston for the first time in their rivalry. They won the first game behind Jerry Wests 53 points, and had a 3–2 lead after five.[52] Boston won the series in seven games however,[53] and earned their 11th NBA Championship in 13 seasons. West was named the first­ever Finals MVP; this remains the only time that a member of the losing team has won the award.',
						'In the 1979 NBA Draft, Los Angeles selected 6­foot, 9­inch point guard Magic Johnson from Michigan State with the first overall pick.[86] It took Johnsons teammates time to acclimate themselves to his passing ability, as his "no­look" passes often caught them unaware. Once they adjusted, his passing became a key part of Los Angeles offense.The Lakers won 60 games in Johnsons rookie year, and defeated the Philadelphia 76ers in six games in the 1980 NBA Finals. Johnson won the series Finals MVP award, after starting at center for the injured Abdul­Jabbar in game six, and tallying 42 points, 15 rebounds, and seven assists. The team fell off in the 1980–81 season, though, as the Lakers lost Johnson for most of the season to a knee injury. The team turned in a 54–28 record and finished second behind the Phoenix Suns in the Pacific Division. The Rockets, led by Moses Malone, defeated Los Angeles in the first round of the playoffs.',
						'Championship banners, Lakers retired jerseys, and honored Minneapolis Lakers banner hanging in the rafters of Staples Center During the 1996 off­season, the Lakers acquired 17­year­old Kobe Bryant from the Charlotte Hornets for Vlade Divac; Bryant was drafted 13th overall out of Lower Merion High School in Ardmore, Pennsylvania in that years draft, by Charlotte. Los Angeles also signed free­agent Shaquille ONeal. Trading for Bryant was Wests idea, and he was influential in the teams signing of the all­star center. "Jerry West is the reason I came to the Lakers," ONeal later said.[133] They used their 24th pick in the draft to select Derek Fisher.[134] During the season, the team traded Cedric Ceballos to Phoenix for Robert Horry. ONeal led the team to a 56–26 record, their best effort since 1990–91, despite missing 31 games due to a knee injury. ONeal averaged 26.2 ppg and 12.5 rpg and finished third in the league in blocked shots (2.88 bpg) in 51 games. The Lakers defeated the Portland Trail Blazers in the first round of the 1997 NBA Playoffs. ONeal scored 46 points in Game 1 against the Trail Blazers, marking the ￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼￼highest single­game playoff scoring output by a Laker since Jerry West scored 53 against the Celtics in 1969. In the next round, the Lakers lost four games to one to the Utah Jazz.'
];

var CelticsInfo = "Team: Boston Celtics Current Season: 25­57 Team Color: Green, White, Black, Gold Best Player: Rajon Rondo Rings: 17 Coach: Brad Stevens President: Danny Ainge City: Boston Massachusetts Conference: Eastern Atlantic Champion Seasons: (1957, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1968, 1969, 1974, 1976, 1981, 1984, 1986, 2008) Owner: Boston Basketball Partners Rivalries: Phila 76ers, LA Lakers, Detroit Pistons, New York Knicks Arena: TD Garden";




var Celtics = [
				"The addition of Bill Russell helped the Boston Celtics win 11 championships in his 13 seasons. With Bill Russell, the Celtics advanced to the NBA Finals and defeated the St. Louis Hawks in seven games, giving the Celtics the first of their record seventeen championships. Russell later won 11 championships, making him the most decorated player in NBA history.[13] In 1958, the Celtics again advanced to the NBA Finals, this time losing to the Hawks in 6 games.[14] However, with the acquisition of K.C. Jones that year, the Celtics began a dynasty that would last for more than a decade.[15] In 1959, the Celtics won the NBA Championship after sweeping the Minneapolis Lakers, the first of their record eight consecutive championships.",		
				"The Celtics owned two of the top eight picks in the 1978 NBA Draft.[29] Since the Celtics had two draft choices, Auerbach took a risk and selected junior Larry Bird of Indiana State with the 6th pick, knowing that Bird would elect to remain in college for his senior year. The Celtics would retain his rights for one year—a rule that was later changed—and Auerbach believed that Bird's potential would make it worth the wait. Auerbach also felt that when the college season ended the Celtics would have a great chance to sign Bird. Auerbach was right and Bird signed soon after leading Indiana State to the NCAA Championship game, where they fell to a Michigan State University team. (The other pick was Freeman Williams, who was traded before the 1978­79 season began.",		
				"In the summer of 2007, GM Danny Ainge made a series of moves that returned the Celtics to prominence. On draft night, he traded the No. 5 pick Jeff Green, Wally Szczerbiak and Delonte West to Seattle for perennial all­star and UConn alum Ray Allen and Seattle's second­round pick which the team used to select LSU's Glen Big Baby Davis.[78] Then the Celtics traded Ryan Gomes, Gerald Green, Al Jefferson, Theo Ratliff, Sebastian Telfair, to Minnesota, where Ainge's former teammate Kevin McHale was the G.M., and swapped 2009 first round draft picks, for MVP Kevin Garnett.[79] These moves created the Boston Three Party (the nickname given to describe the combining of Allen, Garnett, and Pierce by Scott Van Pelt in a This Is Sportscenter commercial), which would revitalize the team and lead them back to glory."	

];

var KnicksInfo = "Best Player: Carmelo Anthony Rings: 2 Coach: Derek Fisher President: Steve Mills City: Boston Massachusetts Conference: Eastern Atlantic Champion Seasons: (1970, 1973) Owner: The Madison Square Garden Company Rivalries: Boston Celtics, Miami Heat, Indiana Pacers, Brooklyn Nets,Chicago Bulls Arena: Madison Square Garden";




var Knicks = [
				"In 1946, basketball, particularly college basketball, was a growing and increasingly profitable sport in New York City.[2] Hockey was another popular sport at the time and generated considerable profits; however, the arenas were not used often.[3] Max Kase, a New York sportswriter, became the sports editor at the Boston American in the 1930s where he met Boston Garden owner Walter A. Brown.[4] Kase developed the idea of an organized professional league to showcase college players upon their graduation and felt it could become profitable if properly assembled.[4] Brown, intrigued by the opportunity to attain additional income when the hockey teams were not playing or on the road, contacted several arena owners.[4] On June 6, 1946, Kase and Brown and a group of seventeen others assembled at the Commodore Hotel in New York City where charter franchises were granted to major cities throughout the country.[5]",
				"As a result of the Knicks' dismal performance in the 1984–85 season, the team was entered into the first­ever NBA Draft Lottery.[41] The team ended up winning the number one pick in that year's NBA Draft. They used the pick to select star center Patrick Ewing of Georgetown University.[41] In Ewing's first season with the Knicks, he led all rookies in scoring (20 points per game) and rebounds (9 rebounds per game), and he won the NBA Rookie of the Year Award.[42] The team would not fare as well, though, as they struggled to a 23–59 record in his first season.[22] During Ewing's second season, the team started with a 4–12 record and head coach Hubie Brown was dismissed in favor of assistant Bob Hill.[43] Under Hill, the Knicks had brief successes but went on to lose seventeen of their twenty­one final games of the season to finish 20–46 under Hill and 24–58 on the season.[44][45] Hill was dismissed at season's end.[46] The team immediately turned around in the 1987–88 season with the hiring of Rick Pitino as head coach, who, only months prior to his hiring, led Providence College to the Final Four, turning around a program that had struggled prior to his arrival.[46] Combined with the selection of point guard Mark Jackson, who won the NBA Rookie of the Year Award and garnered MVP consideration, in the draft and with Ewing's consistently stellar play, the Knicks made the playoffs with a record of 38–44, where they were defeated by the Celtics in the first round.",
				"With the Knicks struggling to an 8–15 record, D'Antoni inserted third­string point guard Jeremy Lin into the rotation against the New Jersey Nets on February 4, 2012.[130] Lin, who had been claimed off waivers on December 27 following an injury to Iman Shumpert, scored 25 points and had 7 assists en route to a Knicks win.[130][132] Lin was praised for his ability to facilitate the offense, something the Knicks had struggled to do for the first 23 games of the season.[130] Lin, exceeding expectations, was named the starter for the Knicks following a game against the Utah Jazz.[133] Lin guided the Knicks to a seven­game winning streak, despite being without Anthony and Amar'e Stoudemire for five games due to a groin injury and a death in the family respectively, that brought the team back to a .500 winning percentage.[134][135][136] The surge of positive play by the Knicks accompanied by the performance of Lin caused extensive national and worldwide media coverage that was referred to as 'Linsanity'.[137] To bolster their depth and perimeter shooting percentage, the Knicks signed J. R. Smith on February 18, 2012.[138] The team struggled to congeal when Anthony returned from injury and went on to lose seven of eight games before head coach Mike D'Antoni resigned on March 14, 2012. Assistant Mike Woodson was named the interim head coach."

];


var BullsInfo = "Team: Chicago Bulls Current Season: 48­34 Team Color: Red, Black, White Best Player: Derrick Rose Rings: 6 Coach: Tom Thibodeau President: John Paxson City: Chicago Illinois Conference: Eastern Central Champion Seasons: (1991, 1992, 1993, 1996, 1997, 1998) Owner: Jerry Reinsdorf Rivalries: Indiana Pacers, Miami Heat, Detroit Pistons, New York Knicks Arena: United Center";



var Bulls = [
				"The Chicago Bulls are the third NBA franchise in Chicago, after the Packers–Zephyrs (now the Washington Wizards) and the Stags (1946–50). The Bulls' founder, Dick Klein, was the Bulls' only owner to ever play professional basketball (for the Chicago American Gears). He served as the Bulls' president and general manager in their initial years. The team started in the 1966–67 NBA season, and posted the best record by an expansion team in NBA history. Coached by Chicagoan and former NBA star Johnny Red Kerr, and led by former NBA assist leader Guy Rodgers and forward Bob Boozer, the Bulls qualified for the playoffs, the only NBA team to do so in their first season.",
				"Michael Jordan was drafted third overall by the Bulls in 1984. He won six championships and six Finals MVPs for Chicago. In the summer of 1984, the Bulls had the third pick of the 1984 NBA Draft, after Houston and Portland. The Rockets selected Hakeem Olajuwon, the Blazers picked Sam Bowie and the Bulls chose shooting guard Michael Jordan. The team, with new management in owner Jerry Reinsdorf and general manager Jerry Krause, decided to rebuild around Jordan. Jordan set franchise records during his rookie campaign for scoring (third in the league) and steals (fourth), and led the Bulls back to the playoffs, where they lost in four games to the Milwaukee Bucks. For his efforts, he was rewarded with a selection to the All­NBA Second Team and the NBA Rookie of the Year Award. In the following offseason, the team acquired point guard John Paxson and on draft day traded with the Cavaliers for the rights to power forward Charles Oakley. Along with Jordan and center Dave Corzine, they provided much of the Bulls' offense for the next two years. After suffering a broken foot early in the 1985–86 season, Jordan finished second on the team to Woolridge in scoring. Jordan returned for the playoffs, and took the eighth­place Bulls against the 67–15 Boston Celtics, led by Larry Bird. At the time, the Bulls had the fifth worst record of any team to qualify for the playoffs in NBA history.[5] Though the Bulls were swept, Jordan recorded a playoff single­game record 63 points in Game 2 (which still stands to this day), prompting Bird to call him 'God disguised as Michael Jordan.'",
				"With a slim 1.7% chance of winning the rights to draft number 1, the Bulls won the 2008 NBA Draft Lottery and selected first overall. With this, the Bulls became the team with the lowest chance of winning to ever win the lottery since it was modified for the 1994 NBA Draft, and second lowest ever. On June 26, 2008, the Bulls drafted Chicago native Derrick Rose from the University of Memphis as the number 1 draft pick. Rose earned the 2011 NBA MVP Award, thereby becoming the youngest player in NBA history to win it. He became the first Bulls player since Michael Jordan to win the award. As a team, Chicago finished the regular season with a league­best 62–20 record and clinched the first seed in the Eastern Conference for the first time since 1998. The Bulls defeated the Indiana Pacers and the Atlanta Hawks in five and six games, respectively,thereby reaching the Eastern Conference finals for the first time since 1998, and faced the Miami Heat. After winning the first game of the series, they lost the next four games, ending their season."
];
